### ISSUE TITLE
NEW FEATURE: Load specific columns in data.frame like objects

### ISSUE THREAD

**Issue by randrescastaneda** [traversc/qs#100]
Hi @traversc , 

It would be great to have an argument in `qread()` that allows the user to specify which columns they want to load. Something similar to the `columns` argument in the [`fst::fst_read()`](https://www.fstpackage.org/reference/write_fst.html) function.  Of course, given that `qs` works for any type of object, including lists, the argument should check whether or not the object that is intended to be loaded is of class `data.frame`. Also, if the object is a simple list, this argument could work to load particular elements of the list. 

Anyway, this is just an idea. If I knew C++, I would have happily contributed 😉 

Thank you so much for this great package!

**Comment by traversc** [comment]
Hi @randrescastaneda thanks for your feedback! This has been asked before, but unfortunately because it needs to work for arbitrary objects and not just dataframes it's not possible to implement sensibly in `qs`. 

`fst` is a great package and if you need just data.frames I highly recommend it. Another package you might look into is `arrow` which has this feature and also has python compatibility.
