### ISSUE TITLE
qs saves include extra items in environments

### ISSUE THREAD

**Issue by kendonB** [traversc/qs#31]
This problem is described for rds's here (since fixed in base R) and occurs when saving via `qs`:

https://stat.ethz.ch/pipermail/r-devel/2016-July/072924.html

In short, qs seems to serialize all objects in an enclosing environment when writing items that include environments such as `lm` or `ggplot`.

``` r
save_size_qs <- function (object) {
  tf <- tempfile(fileext = ".qs")
  on.exit(unlink(tf))
  qs::qsave(object, file = tf)
  file.size(tf)
}

save_size_rds <- function (object) {
  tf <- tempfile(fileext = ".rds")
  on.exit(unlink(tf))
  saveRDS(object, file = tf)
  file.size(tf)
}

normal_lm <- function(){
  junk <- 1:1e+08
  lm(Sepal.Length ~ Sepal.Width, data = iris)
}

normal_ggplot <- function(){
  junk <- 1:1e+08
  ggplot2::ggplot()
}

clean_lm <- function () {
  junk <- 1:1e+08
  # Run the lm in its own environment
  env <- new.env(parent = globalenv())
  env$subset <- subset
  with(env, lm(Sepal.Length ~ Sepal.Width, data = iris))
}

# The qs save size includes the junk but the rds does not
save_size_qs(normal_lm())
#> [1] 848396
save_size_rds(normal_lm())
#> [1] 4178
save_size_qs(normal_ggplot())
#> [1] 857446
save_size_rds(normal_ggplot())
#> [1] 12894

# Both exclude the junk when separating the lm into its own environment
save_size_qs(clean_lm())
#> [1] 6154
save_size_rds(clean_lm())
#> [1] 4273
```

<sup>Created on 2020-01-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kendonB** [comment]
@wlandau fyi

**Comment by kendonB** [comment]
Possibly related: https://github.com/traversc/qs/issues/21

**Comment by traversc** [comment]
Hi @kendonB , the issue is not environment, but `junk <- 1:1e+08` being an ALT-REP, which is a special type of object.  Let me explain, but first try this:

```
normal_lm <- function(){
  set.seed(1); junk <- runif(1e7) # <---- change from your original code
  lm(Sepal.Length ~ Sepal.Width, data = iris)
}

normal_ggplot <- function(){
  set.seed(1); junk <- runif(1e7)
  ggplot2::ggplot()
}

clean_lm <- function () {
  set.seed(1); junk <- runif(1e7) 
  # Run the lm in its own environment
  env <- new.env(parent = globalenv())
  env$subset <- subset
  with(env, lm(Sepal.Length ~ Sepal.Width, data = iris))
}

save_size_qs(normal_lm())
#> [1] 41807225
save_size_rds(normal_lm())
#> [1] 53264446
```

You can see that for other types of objects, the compressed sizes are  similar.  In R 3.6, `rds` uses a new format that serializes ALT-REP objects in a different way.  Effectively, `rds` only saves the `1` and `1e8` in `1:1e8`.  

I could do this with `qs`, but it'll take some work and I don't view this as a high priority, since the compression of `1:1e8` is already quite efficient.  `1:1e8` is ~400 Mb expanded in memeory, and `qs` compresses that down to 800 Kb.
