### ISSUE TITLE
feature request: add meta data to qs file

### ISSUE THREAD

**Issue by statquant** [traversc/qs#66]
Hello, 
FIrst, thanks again for the amazing package.
I have a feature request that I hope you'll find useful:
I think that would be extremely useful to be able to add meta data to a qs file. For instance say you save a table with say a column date, it could be useful to know the date range saved in the table. In everything that involves caching (and I think everyone caching stuff is using qs or fst) it comes super handy.
fst offers some flavor of it (typically column classes), the way I see it a function like the below would do the trick, and by default simple meta data could be attached (column type, nrow, ncol for data.frame (and inherits), ...)
```
add_metadata <- function(path, data) {
 # attach data to qs file 
}
```

Many thanks

**Comment by traversc** [comment]
I would be opposed to building in metadata directly to the qs file format, because I see it as more of a convenience feature (since you could simply store metadata externally) and not something core. It adds complexity and the possibility of additional bugs. 

However, if it's a pure R convenience function written on top qs somehow, that would be a possibility. Can you expand on how that would look like? If you add metadata, where would it be stored?
