### ISSUE TITLE
DESCRIPTION file broken?

### ISSUE THREAD

**Issue by tuxmaster5000** [traversc/qs#91]
The guys from Posit have found out, that an error in the file will prevent the build of the module for the package manager.
Here are the link for the problem description.
https://community.rstudio.com/t/qs-binary-package-for-r-4-3-and-rhel-9-is-missing/183207/2

**Comment by traversc** [comment]
Thanks for the link, repsonding in rstudio forum

**Comment by traversc** [comment]
@barracuda156 I changed the way to check for the -latomic flag because of this issue.

https://github.com/traversc/qs/blob/master/configure.ac#L63

Would it be possible to confirm that the latest commit still works on your system?

**Comment by barracuda156** [comment]
@traversc This will not work, AFAIU, since we need to check for 8-byte atomics: using `int` will check for 4-byte atomics support, which will not need `libatomic`.

**Comment by barracuda156** [comment]
P. S. I am not aware of situations where 4-byte atomics needs `libatomic`, to be honest. Normally what needs it is 8-byte atomics, which is not supported on a hardware level on 32-bit archs. So that should be checked.
I have seen elsewhere that RISC-V needs to check for 1-byte atomics, but cannot confirm that personally.

**Comment by traversc** [comment]
Got it, I added all the atomic types used in the package, should work now :)

https://github.com/traversc/qs/blob/master/configure.ac#L63

**Comment by traversc** [comment]
Closed to consolidate discussion. See: https://github.com/traversc/qs/issues/88
